### ISSUE TITLE
!! Not an issue !! Tv Shows

### ISSUE THREAD

**Issue by the-poor-gamer-124** [redmusicxd/iptv_ro#12]
Hello! Can Tv shows and "emisiuni" from antena be showed only by year, not also month?

**Comment by redmusicxd** [comment]
Unfortunately no, it is a limitation of their system, you can only filter
by month & year.

**Comment by the-poor-gamer-124** [comment]
Ok. Can you help me add a few more elements to that html

**Comment by redmusicxd** [comment]
Sure, what do you need?

**Comment by the-poor-gamer-124** [comment]
Some css. Also, with digi, since my ipv4 is blocked, can I use my IPV6

**Comment by the-poor-gamer-124** [comment]
For streams*y

**Comment by redmusicxd** [comment]
No CSS as the scope of the html was just for testing purposes, in the
future will be in JSON format but I didn’t had the time or the mood to do
so, like all the other things for this project.
As for the ipv6, afaik their stream servers are only ipv4 so you can’t
access it from an ipv6 address.

**Comment by the-poor-gamer-124** [comment]
ah, ok

**Comment by the-poor-gamer-124** [comment]
I cannot wait for JSON format

**Comment by the-poor-gamer-124** [comment]
Anwyays, until then, maybe you can make it easier to modify HTML?

**Comment by redmusicxd** [comment]
what do you mean?

**Comment by the-poor-gamer-124** [comment]
having an external html file ? 

also do you use discord?

**Comment by redmusicxd** [comment]
actually right now i'm working on replacing the HTML with JSON as it's been due for some time now and yes, i do use discord.

**Comment by the-poor-gamer-124** [comment]
can you give me your @ and #

sâm., 27 mar. 2021, 16:17 Dan Negru ***@***.***> a scris:

**Comment by redmusicxd** [comment]
rednblkx#6553
