### ISSUE TITLE
Undefine

### ISSUE THREAD

**Issue by eplayerclick** [redmusicxd/iptv_ro#13]
Good day 
All antena channels redirect to http://localhost:3000/mireasa

Can you assist me with this?

**Comment by redmusicxd** [comment]
Hi,

Will check it later and get back to you

**Comment by eplayerclick** [comment]
Ok

**Comment by eplayerclick** [comment]
also , very often i see json error
antena| getStream: antena| getLogin: SyntaxError: Unexpected token } in JSON at position 2082

**Comment by eplayerclick** [comment]
![image](https://user-images.githubusercontent.com/90185126/133802781-fcf6de3d-7107-469c-9858-a1836e0cd8cf.png)

**Comment by redmusicxd** [comment]
What version of node you using?
Try a newer version

**Comment by eplayerclick** [comment]
should be latestr

**Comment by eplayerclick** [comment]
antena| getStream: antena| getLogin: antena| login: Error: Request failed with status code 429

**Comment by redmusicxd** [comment]
429 means too many requests

**Comment by eplayerclick** [comment]
but i barely requested their server

**Comment by redmusicxd** [comment]
Issue should be fixed now by commit 75d37e1
