### ISSUE TITLE
Error NOTFOUND antena shows

### ISSUE THREAD

**Issue by redmusicxd** [redmusicxd/iptv_ro#16]
Something happened on the recent commits, error will be fixed in the next commit

**Comment by eplayerclick** [comment]
Ok, thanks for your time and making this script free

**Comment by eplayerclick** [comment]
![image](https://user-images.githubusercontent.com/90185126/135133956-608032e4-aa2b-4659-8cdf-dc48a923926f.png)

**Comment by eplayerclick** [comment]
many times this happens

**Comment by redmusicxd** [comment]
reported error cannot be reproduced however it may be fixed by 256b8182ce24dcb08832df7da6c8a966e98adac0, initial error is bogus, closing issue
