### ISSUE TITLE
Cannot read property 'data'  - on protv.js

### ISSUE THREAD

**Issue by staycanuca** [redmusicxd/iptv_ro#2]
TypeError: Cannot read property 'data' of undefined
    at C:\xxxxxxxxx\protv.js:55:32
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
login: TypeError: Cannot read property 'data' of undefined
(node:8360) UnhandledPromiseRejectionWarning: getPlaylist: login: TypeError: Cannot read property 'data' of undefined
(node:8360) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

Thank you and  "La multi ani"

**Comment by redmusicxd** [comment]
La multi ani
Please check your username & password
