### ISSUE TITLE
digi error

### ISSUE THREAD

**Issue by staycanuca** [redmusicxd/iptv_ro#3]
hi,
I got this error when I try to poitn my browser to:
http://localhost:3000/kanal-d?ts=1&quality=hq   error is:

digi| getLogin: digi| login: Error: Failed to launch the browser process! /home/pi/Documents/iptvro/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome: 1: /home/pi/Documents/iptvro/node_modules/puppeteer/.local-chromium/linux-818858/chrome-linux/chrome: Syntax error: "(" unexpected TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

and one more error: even that 5 free digi links are not working in vlc

Thank you for a good script!

**Comment by redmusicxd** [comment]
Not sure what’s wrong I’ll take a look tomorrow and about the other error
tell me more about it

**Comment by staycanuca** [comment]
Salut - cand incerc sa rulez orice link digi in vlc - si aici vb despre cele 5 streamuri free - nu porneste nimic. 
In momentul cand accesez unul dintre cele 5 linkuri in browser, imi descarca m3u8 cu canalul respectiv,
Linkurile sunt de format: http://localhost:3000/digi24.m3u8

**Comment by redmusicxd** [comment]
1. Prima problema se pare că este cauzată de faptul că browser-ul chromium folosit by default de către modulul puppeteer nu se descarcă pentru arhitectura arm, o soluție temporara este rularea pe un sistem cu arhitectura x86_64 și apoi copierea fișierului auth.json pe sistemul cu arm
2. Problema cu vlc-ul este rezolvată

**Comment by staycanuca** [comment]
- a doua problema e intradevar rezolvata.
- inca nu imi porneste chromium atat pe arm cat si pe doua sisteme cu w10
