### ISSUE TITLE
Digi streams have cors

### ISSUE THREAD

**Issue by the-poor-gamer-124** [redmusicxd/iptv_ro#4]
Digi streams have now CORS / ACAO on them, maybe a dynamic proxying of the specific node ( edge ) you get assigned to might fix this?

**Comment by redmusicxd** [comment]
Have you tried the ts parameter ? like local host:3000/[channel].m3u8?ts=1

**Comment by the-poor-gamer-124** [comment]
It is also on the ts files, i think the best solution would be to proxy the ts files as well 

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

**Comment by redmusicxd** [comment]
Figured you would say that, I’ll see what I can do

**Comment by the-poor-gamer-124** [comment]
also do you use telegram?

**Comment by redmusicxd** [comment]
Not actively

**Comment by the-poor-gamer-124** [comment]
Easiest way to do it is to proxy the token's folder ( https://edge212.rcs-rds.ro/V5-1359250-b03c348749fbaa692444c53818976577-3111686696-0-1612461414-1-digisport1-2e9d6d8e44b87e5e/digionline/  for example  )  on ip:3000/channel so i can access it on 
https://ip:3000/digisport1-abr.m3u8?is=1&ns=digisport1&p=Browser&s=site&sn=digionline.ro&t=00000000000000000000000000000000&t4=V4-4051337-f0a56dbac1fb4426f5a4ff68987c010b-3111686696-0-1612461414-1-digisport1&t5=V5-1359250-b03c348749fbaa692444c53818976577-3111686696-0-1612461414-1-digisport1-2e9d6d8e44b87e5e and ts files in same folder

**Comment by redmusicxd** [comment]
Thanks for the suggestion, I’ll try that when I can

**Comment by the-poor-gamer-124** [comment]
Ok, hopefully you have luck!

**Comment by redmusicxd** [comment]
Unfortunately I didn't have any luck in implementing such thing so until I figure it out I suggest you use something like this project https://github.com/warren-bank/HLS-Proxy, I'll close this issue for now.

**Comment by the-poor-gamer-124** [comment]
Unfortunately ( sorry to bug you btw ) i cannot seem to get it working with this script on the same VPS... :(

**Comment by the-poor-gamer-124** [comment]
How would i specify where it should find the stream?

**Comment by redmusicxd** [comment]
> Unfortunately ( sorry to bug you btw ) i cannot seem to get it working with this script on the same VPS... :(

email me the details

**Comment by the-poor-gamer-124** [comment]
also, what setup do you recomend since there are a lot of channels on digi ( which i want all )

**Comment by the-poor-gamer-124** [comment]
Would it be possible to get assigned to a specific edge on their servers?

**Comment by redmusicxd** [comment]
Well no, also not helping solving the issue.

**Comment by the-poor-gamer-124** [comment]
It would since i could nginx reverse proxy the node itself

**Comment by redmusicxd** [comment]
Well then just reverse proxy the api’s channel endpoint (
http://localhost:3000/:channel)

**Comment by the-poor-gamer-124** [comment]
![Screenshot_20210206-002837_Edge](https://user-images.githubusercontent.com/46222936/107095979-6948a280-6812-11eb-9a8d-c4c1a6d0cad8.jpg)
Getting a lot of these lately

**Comment by redmusicxd** [comment]
Yeah seems to be a problem with the free channels I’ll have to investigate,
thanks for letting me know

**Comment by the-poor-gamer-124** [comment]
Not only free ones digi online ones also

**Comment by the-poor-gamer-124** [comment]
But restarting the thing (killing nodejs and starting it again) fixes it ( temporarily)

**Comment by redmusicxd** [comment]
It’s probably because I configured it to cache the url and then remove it after a few hours

**Comment by redmusicxd** [comment]
Please if you have comments unrelated to this issue please email me or open a new issue if you have a problem like this

**Comment by the-poor-gamer-124** [comment]
cel mai convenabil e sa se stearga acel cache la prima eroare 403

**Comment by redmusicxd** [comment]
N-ar trebui sa fie nicio eroare 403, când se întâmplă asta?

**Comment by the-poor-gamer-124** [comment]
uneori si la 1 ora dupa ce a fost scos stream

vin., 5 mar. 2021, 21:17 Dan Negru <notifications@github.com> a scris:

**Comment by redmusicxd** [comment]
O sa îmbunătățesc error handling-ul ca sa adreseze situațiile in care
primește eroare la o cerere, cum ar fi cea menționata de tine.
