### ISSUE TITLE
Antena

### ISSUE THREAD

**Issue by the-poor-gamer-124** [redmusicxd/iptv_ro#6]
Since antena's streams are IP based, maybe a system similar to the VLC block bypass ( Note 2: For VLC use the "ts=1" query string(this is because digi banned the ffmpeg & VLC user-agents from accessing the main playlist but not the playlists with the .ts files)   )  shall also be integrated with antenaplay?

**Comment by redmusicxd** [comment]
It is on plan to implement that, I just forgot about it.

**Comment by redmusicxd** [comment]
even thought i didn't encounter any problems with the stream so far

**Comment by the-poor-gamer-124** [comment]
yes but it is ip blocked, if someone need to share it's not gonna work.

**Comment by redmusicxd** [comment]
Oh, I see now, you are talking about watching outside Romania, yeah well
the only solution for that is to route the stream through a VPN

**Comment by the-poor-gamer-124** [comment]
Nonono, the token is blocked to the IP you get it to 
if i use script on ip 1.1.1.1 it wont work on 1.1.0.1

**Comment by redmusicxd** [comment]
Then the ts param should help as the segment files are not protected by a token AFAIK

**Comment by redmusicxd** [comment]
Solved by commit f7d843cd9c7f88742c54b12457eff9bba4e82e21

**Comment by the-poor-gamer-124** [comment]
https://prnt.sc/yfcbnr

antena international

**Comment by the-poor-gamer-124** [comment]
yes and also mireasa live

**Comment by the-poor-gamer-124** [comment]
Is there an EPG for antena / PRO-

**Comment by redmusicxd** [comment]
no afaik

**Comment by redmusicxd** [comment]
i'm sure there is an API, just didn't discovered it

**Comment by the-poor-gamer-124** [comment]
curl -X POST -H "Content-Type:application/x-www-form-urlencoded" -H "User-Agent:Dalvik/2.1.0 (Linux; U; Android 10; SM-J600FN Build/QP1A.190711.020)" -H "Host:api.antenaplay.ro" -H "Connection:Keep-Alive" -H "Accept-Encoding:gzip" -H "Content-Length:139" -d "{"request":"{"client_id":24,"function":"getChannelList","parameters":[{}]}","signature":"6f68014b4e5a318a200786c35764fae4804880a2"}" "https://api.antenaplay.ro/"

**Comment by the-poor-gamer-124** [comment]
am gasit asta in app antenaplay

**Comment by redmusicxd** [comment]
chiar nu m-am gandit sa inspectez aplicatia

**Comment by the-poor-gamer-124** [comment]
da dar o sa fie problema cu semnatura aia, in rest ar trb sa fie ok

**Comment by the-poor-gamer-124** [comment]
PRO TV GRABBER PHP fara cont :)

<?php
    header("Access-Control-Allow-Origin: https://canale.live");

$url = "https://media.cms.protvplus.ro/embed/9w1VHN18dnM?autoplay=1";
$json=file_get_contents("linepro.json");
$line=json_decode($json,true);
$file = file($url);
$str1 = str_replace(array('Player.init(\'player-1\', {"tracks":{"HLS":[{"src":"', '","type":"application\/x-mpegURL"}]},"duration":null,"plugins":{"adService":{"type":"ima","vpaidVolumeSync":true,"settings":{"linear":[],"imaOptions":{"contribAdsSettings":{"prerollTimeout":5000}}},"linear":{"preroll":{"vasts":["https:\/\/securepubads.g.doubleclick.net\/gampad\/ads?env=vp&gdfp_req=1&output=vast&sz=640x480&unviewed_position_start=0&ad_rule=0&vad_type=linear&vpos=preroll&pmad=2&pmxd=60000&description_url=https%3A%2F%2Fprotvplus.ro%2Ftv-live%2F1-pro-tv&iu=%2F36564804%2Fprotvplusro%2Fdesktop%2Fpreroll&cust_params=hostname%3Dprotvplus.ro%26title%3DPRO_TV%26show%3Dlive&max_ad_duration=30000"]}}},"measuring":{"streamInfo":{"programID":"fd2967d3-7c3a-49df-89e0-713c63b68ec4","programName":"Pro TV live - CRa","programType":"Video","videoType":"VOD","playerType":"player","programDuration":-1,"videoID":"fd2967d3-7c3a-49df-89e0-713c63b68ec4"},"services":[]},"markers":{"markerTip":{"display":false},"markers":[]},"playedTicks":[],"settings":{"languages":[],"qualities":[]},"mobileControls":{"inactivityTimeout":5000}},"autoplay":true,"preferredLang":["rum"],"language":"ro"}, {"video":{"identifier":"fd2967d3-7c3a-49df-89e0-713c63b68ec4","type":"live","title":"Pro TV live - CRa","description":null,"duration":null,"custom":[]},"preview":false,"trackingCharts":"","k_events":["init","autoplayfailure","restricted","error","pause","resume","recurring"]});'), "", $file[$line["linie"]]);
$str1 = str_replace("\\", "", $str1);
header("Location: ".$str1);
?>


scz ca e offtopic dar nu aveam unde sa il pun ;-; ( nu avea rost sa fac issue )

**Comment by redmusicxd** [comment]
da un link si pentru chestii offtopic trimite-mi pe email ca oricum primesc notificare de la GitHub asa ca e tot aia.

**Comment by redmusicxd** [comment]
canalele antena pot fi accesate la o adresa ca urmatoarea https://live7digi.antenaplay.ro/channel/channel.m3u8 ( inlocuieste channel cu id-ul canalului gen a1, happy, zutv ) , folosind un proxy ca acesta https://github.com/warren-bank/HLS-Proxy iti rezolva toate problemele.

**Comment by the-poor-gamer-124** [comment]
auci, si eu ma chinui cu tokene ca prostul..

Pe 12.02.2021, Dan Negru <notifications@github.com> a scris:

**Comment by redmusicxd** [comment]
oricum si eu am descoperit recent asta accidental

**Comment by the-poor-gamer-124** [comment]
am observat ca acel link nu merge pe alte servere doar pe live7digi

**Comment by the-poor-gamer-124** [comment]
Se poate acel parametru TS si pe VOD? sau emisiuni

**Comment by redmusicxd** [comment]
da, chiar am sa incerc sa implementez ceva global ca momentan este provider-specific implementat si nu l-am adaugat la toate platformele.

**Comment by the-poor-gamer-124** [comment]
oricum abia astept refactorizarea unde vom putea alege daca facem cache si vom putea folosi mai putine resurse :D

**Comment by redmusicxd** [comment]
Din păcate, încă sunt la inceput așa că o să dureze până o să ajung să-l
fac eficient, cat despre refactorizare nu mai este o prioritate deoarece
vreau să mă asigur mai întâi că totul este cum trebuie și după mă apuc să
rescriu dar voi implementa o mai bună administrare a cache-ului.
