### ISSUE TITLE
FilmNow

### ISSUE THREAD

**Issue by the-poor-gamer-124** [redmusicxd/iptv_ro#9]
Hello. Would it be possible to grab filmnow dash links.?

**Comment by redmusicxd** [comment]
Yeah, sure, I'll make it available in JSON format so you receive an object
with the manifest & widevine proxy URLs

**Comment by the-poor-gamer-124** [comment]
super cool

**Comment by the-poor-gamer-124** [comment]
but the widevine is static

**Comment by redmusicxd** [comment]
Doesn’t matter.

**Comment by the-poor-gamer-124** [comment]
Yes since it can change at any time

2021-02-27 22:18 GMT+02:00, Dan Negru <notifications@github.com>:

**Comment by redmusicxd** [comment]
solved by ab443bc40d248b86aa41b191b64f670066108b9c
